development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://zgytdkkfynwrom:45f14ae63e247705e088e21f42f9c87c6f17466aa8cd470c1ef1533df682aa7c@ec2-54-225-107-107.compute-1.amazonaws.com:5432/d7ojc2elt25sku
